### ISSUE TITLE
Support `dollar templating` in config file

### ISSUE THREAD

**Issue by pspiagicw** [pspiagicw/dotback#10]
Right now the `after-backup` commands are written completely by the user.

But we should provide some resolving of the commands using `demp`.

Let me explain

```toml
storeDir = "some-system-path"
after-backup = [
    "tar -czvf backup.tar.gz <the-full-fucking-path>"
]
```

What if we support `dollar templating` like we use for `groom`.
Meaning

```toml
storeDir = "some-system-path"
after-backup = [
    "tar -czvf backup.tar.gz $storeDir"
]
```

It makes it easier for the user to build upon complex commands.
Like

```toml
storeDir = "some-system-path"
after-backup = [
    "tar -C $storeDir -czvf backup.tar.gz $storeDir",
    "scp ${storeDir}/backup.tar.gz <some-server>",
# Either delete the `backup.tar.gz` or not, dotback will work.
    "rm ${storeDir}/backup.tar.gz"
]
```
